### ISSUE TITLE
DTU evaluation in matlab

### ISSUE THREAD

**Issue by gangweix** [FangjinhuaWang/IterMVS#5]
Hi, great work! The evaluate time is very long  in matlab. According to your code, I use eval.py to generate the point cloud first, then download it to the personal computer and use matlab to evaluate the point cloud, but the evaluation time of matlab is too long? Is there a faster way to evaluate？

**Comment by FangjinhuaWang** [comment]
Hi, you can have a look at this: https://github.com/jzhangbs/DTUeval-python

**Comment by gangweix** [comment]
Ok, thanks.

**Comment by gangweix** [comment]
Hi, when I use https://github.com/jzhangbs/DTUeval-python, I encountered an error.

TriangleMesh with 51069949 points and 0 triangles.
sample pcd from mesh: 11%|█████ | 1/9 [00:07<01:02, 7.76s/it]Traceback (most recent call last):
File "pc_eval.py", line 70, in
new_pts = np.concatenate(new_pts, axis=0)
File "<array_function internals>", line 180, in concatenate
ValueError: need at least one array to concatenate.

I use the IterMVS (CVPR 2022) to generate .ply, however during the evaluation, I encountered an error that there is no triangles, how can I solve it？Thanks!
