### ISSUE TITLE
infer with sky mask

### ISSUE THREAD

**Issue by cv-lab-x** [FangjinhuaWang/IterMVS#8]
hi, thanks for your great work, how to infer depth map with sky mask ?  the results of outdoor scene are not good, lots of artifacts on the sky. Looking forward to your reply, thanks. @FangjinhuaWang

**Comment by FangjinhuaWang** [comment]
Hi. The sky is a common issue for exisiting MVS frameworks. If you have sky mask already, I think the easiest way is to use it during photometric filtering [here](https://github.com/FangjinhuaWang/IterMVS/blob/afb870c2d3e15b15e15f244f8d6822c4acb207d5/eval.py#L236). You can combine photo mask with the sky mask such that the photometric confidence of sky regions will be set to 0.

**Comment by cv-lab-x** [comment]
> Hi. The sky is a common issue for exisiting MVS frameworks. If you have sky mask already, I think the easiest way is to use it during photometric filtering [here](https://github.com/FangjinhuaWang/IterMVS/blob/afb870c2d3e15b15e15f244f8d6822c4acb207d5/eval.py#L236). You can combine photo mask with the sky mask such that the photometric confidence of sky regions will be set to 0.

thanks for your reply, if input image with sky mask to mvs network to infer depths, will the results be better than input sky mask during photometric filtering ? @FangjinhuaWang

**Comment by FangjinhuaWang** [comment]
one potential way may be that you manually set the depth range of sky pixels with large depth_min and depth_max.
